install.packages("dplyr")
library(dplyr)

data(iris)
head(iris)
tapply(iris$Sepal.Length, iris$Species, mean)
subset(iris, Species == "setosa" & Sepal.Length > 5.5)
NROW(iris)
print("hello world")
print("git branch made")
print("git branch version2")